spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_ordering_system
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false

authentication-properties:
  security:
    authentication:
      jwt:
        secret: myXAuthSecret
        token-validity-in-seconds: 7200

zuul:
  routes:
    restaurant-ordering-system:
      path: /main/**
      serviceId: restaurant-ordering-system
      stripPrefix: false

server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: qwerty
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
