spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true

authentication-properties:
  security:
    authentication:
      jwt:
        secret: myXAuthSecret
        tokenValidityInSeconds: 7200
  rememberme:
    # security key (this key should be unique for your application, and kept secret)
    key: ee4df72e0480044112ea60b7659b297e6f988f7c

zuul:
  routes:
    cloud:
      path: /main/**
      sensitiveHeaders:
      url: http://localhost:8081
      stripPrefix: false

server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: qwerty
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
